### ISSUE TITLE
Please document the way to maintain a custom extension repository

### ISSUE THREAD

**Issue by stof** [heroku/heroku-buildpack-php#157]
Such repository should not need to contain the PHP packages. It should contain only additional packages on top of the heroku default package, to avoid duplicating the maintenance work

**Comment by dzuelke** [comment]
Well, there is https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md :)

Do you mean the problem that PHP needs to be in that repo so builds in there work? Yeah I guess that's true. This would be a feature for Bob though; `S3_UPSTREAM_BUCKET` and `S3_UPSTREAM_PREFIX`. Want to send a PR to https://github.com/kennethreitz/bob-builder ? ;)

**Comment by dzuelke** [comment]
@stof https://github.com/kennethreitz/bob-builder/pull/21 /cc @kennethreitz

**Comment by stof** [comment]
> Do you mean the problem that PHP needs to be in that repo so builds in there work? Yeah I guess that's true

The issue with that would be that composer may then take PHP from my custom repo rather than the official repo (due to repository priority), which means I would have to ensure that the repo is always in sync to avoid people getting outdated versions while you already updated it. This is why I consider it as an issue.

> This would be a feature for Bob though; S3_UPSTREAM_BUCKET and S3_UPSTREAM_PREFIX. Want to send a PR to https://github.com/kennethreitz/bob-builder

I don't have lots of time right now (and I already have a huge TODO list for projects I maintain to be honest), and the last time I wrote Python was years ago at school. So I'm not sure I will be able to do it. I will open a feature request though, in case someone has time to do it before I do.

Thus, I have not yet migrated to the official PHP buildpack at work (I actually depend on removing the ext-ssh2 extension in my project, and having ext-amqp support in the buildpack for that, and the second part might justify the work there)

**Comment by dzuelke** [comment]
Hah, timing ;) take a look at that bob-builder PR!

**Comment by stof** [comment]
OK, great that you were able to implement the feature in bob that fast :smile:

**Comment by dzuelke** [comment]
It could even support an arbitrary amount of upstream buckets and then a poor soul could take on the task of maintaining underlying libs ;)

**Comment by dzuelke** [comment]
By the way, the libraries used by the buildpack now also create composer packages (but not for deploy time fetching, only for package builds), so they get synced too. See https://github.com/heroku/heroku-buildpack-php/commit/18fee7fda23de0b3bcbd619cd47cab05dbb24e59

**Comment by dzuelke** [comment]
(and same for the Composer and minimal bootstrap PHP versions)

**Comment by dzuelke** [comment]
(also, develop branch has code that fetches composer and minimal PHP from the first bucket instead of the hardcoded default one, in case someone wants to fully reset the bucket used, or if I want to test a new composer version before release without having it in the stable bucket)

**Comment by dzuelke** [comment]
This is now in bob 0.0.10, and the develop branch uses that. Rolling out to master on Thursday. Should have some docs updates in place by then too!

**Comment by dzuelke** [comment]
Check out 30f97f8 @stof

**Comment by dzuelke** [comment]
(and @stesie too)

**Comment by dzuelke** [comment]
You can, by the way, @stof, also just "bob deploy" the PHP requirements, without using `deploy.sh`. Then the archive is in the bucket, but it's not part of the repo, because the manifest is not there.

**Comment by dzuelke** [comment]
Was this helpful @stof?

**Comment by stof** [comment]
@dzuelke I haven't yet tried it, as I'm not yet trying to migrate to the official buildpack (I need to get rid of the ext-ssh2 dependency first, which is in progress).

There is one point I need to figure out, but maybe you have an idea: what would be the right way to access these util scripts when dealing with our own repo of bob formulae rather that the official buildpack ?

**Comment by dzuelke** [comment]
I think I'd simply fork the buildpack and use a branch to maintain custom formulae. Then you can periodically merge from upstream.

**Comment by stof** [comment]
@dzuelke but this would mean that the formulae I would maintain would get mixed with upstream formulae, making it harder to follow for contributors (and also that all the buildpack logic is copied there and people might start trying to contribute to it)

**Comment by dzuelke** [comment]
Yeah. Any other suggestions?

**Comment by stesie** [comment]
@dzuelke I think the extra documentation is helpful and well written (so I haven't really tried it out, since I went on with the earlier version). And indeed the main question to me also was whether to just fork the repository and mix the additions in or to make a new repo and copy over the needed files (i.e. the _util folder). So yes, I'd vote to explicitly state some kind of "best practise" ...

... as you might have seen I decided to create a new repo (and copy those files).  With the other approach I don't that the "essence" of the repository (in most cases just a few files) is well hidden between many many files from upstream ... and as a bonus the repo can have a different name then (`heroku-v8js` vs. `heroku-buildpack-php`)  
 ... on the downside: I have to copy the _util stuff from time to time (and need to hope no one tries to improve them on the "forked" side)

**Comment by dzuelke** [comment]
Well let's brainstorm a little. The build stuff could live in its own repo and be (or not even) a subtree. That makes it hard to keep things in sync though I think.

Package management may be an option ;) The buildpack is already a Composer package. Your repo could have a `composer.json` that requires it, and you then invoke `vendor/heroku/heroku-buildpack-php/support/build/_util/deploy.sh`. Not pretty, but gets the job done. But then you need Composer and PHP on the dyno or Docker container, which more or less rules that out.

http://www.bpkg.io is a crazier option obviously.

I am currently trying to figure out if I can make the whole thing, or a subdir, a pip package. Then instead of `s3cmd` and `bob`, you'd just depend on this github repo here.

I guess one crucial question is... do you just want the utils, or the formulae as well (e.g. do build upon the existing `pecl` base formula)?

**Comment by dzuelke** [comment]
The pip approach may work. Not sure if I'll have time to finalize this at all this week; may have to wait until next.

**Comment by stesie** [comment]
I haven't used pip as a dev so far, can't tell if it may work. But if it does it feels like the best option to me.

I agree that the composer option isn't viable as it isn't available from the python buildpack. Same goes for bpkg (so I haven't used that neither)

Regarding your question whether you only need the utils or the formulae as well ... for v8js I haven't used the pecl formulae as base since the extension needs another library, hence I had to do the xxx-bare dance there. So to me it doesn't feel necessary to ship the pecl formula with the pip package (and if I could still copy it -- it's way more code then the other _util infrastructure) ... and I don't think the other formulae are needed

A different question that came to my mind recently is ... how can the extensions formulae depend on "just any php-7.0.x" instead of hardcoding a single version. Just noticed that both master and develop branch are currently broken since they require "php-7.0.4", but the repo actually provides "php-7.0.5"

**Comment by dzuelke** [comment]
I might actually move the pecl "helper" to util instead. That would solve that neatly.

For depending on "wildcards", that'd be a Bob feature. Feel free to implement it ;)

Bob itself is not all that complicated though. Maybe I can/should replace it with a bunch of shells scripts that use s3cmd. But better to build on something existing I guess!

**Comment by dzuelke** [comment]
(I need to add to my checklist/playbook for PHP updates that all formula dep headers need bumping; it's just a matter of discipline really)

**Comment by stesie** [comment]
... well adding to your checklist solves it for this repository. But not for the others (like heroku-v8js) ... wildcard dependencies would solve both though.

So yes, I should have a look at Bob then ...

**Comment by stof** [comment]
@stesie FYI, when building my own repository of extensions, I used a submodule to bring in the official buildpack: https://github.com/Incenteev/heroku-php-exts
