### ISSUE TITLE
serialize() in cURL & magic_quotes_gpc

### ISSUE THREAD

**Issue by Nekress** [heroku/heroku-buildpack-php#190]
Do I need to clone this entire repo and make my own buildpack in order to disable magic_quotes_gpc in the php.ini or is there another way? It is ruining my serialized objects by escaping the quotes on the servers end.

**Comment by dzuelke** [comment]
`magic_quotes_gpc` is not enabled on Heroku.

It can't be enabled anyway, as the setting was removed in PHP 5.4, which you can't even run on Heroku because it's so old.

Also, `magic_quotes_gpc` never affected output, just input from a request.

You do not need to fork the buildpack. For customizing INI settings, please refer to the documentation: https://devcenter.heroku.com/articles/custom-php-settings#php-runtime-settings
