### ISSUE TITLE
How to add apache modules?

### ISSUE THREAD

**Issue by luka-zitnik** [heroku/heroku-buildpack-php#220]
Hi,

How would you go about building additional apache modules?

Here's what I have so far. Additional apache modules could not be built separately the way php extensions are because composer wouldn't know how to require that. They could not be built separately the way libraries are because apache has to be built first and libraries work the other way round.

So, in order to get it working, I've sourced a script `/support/build/modules/modsecurity-2.9.1` from a convenient place inside `/support/build/apache`. But then every apache version would use the same version of modsecurity.

That may not be too bad considering users of the buildpack don't choose apache version, and there's only one apache version, so there's no problem to solve. But I was curious what would you do in case I made a request that this buildpack ships with modsecurity. Would you make up another marker for Bob, like the `DEPS_MARKER`?

**Comment by luka-zitnik** [comment]
What do you think about that compared to having another package type, like `heroku-sys-apache-module`? Then a package like `heroku-sys-apache-module/modsecurity` could be built separately. It could depend on a specific version of apache and `/support/build/apache` wouldn't have to know about it.

**Comment by dzuelke** [comment]
Hi!

So, right now, you need to build any additional modules into Apache, that's correct.

The problem with it being its own package is... how would you specify its installation?

**Comment by luka-zitnik** [comment]
Hi David!

I was thinking about listing it right after [line 158 of `/bin/util/platform.php`](https://github.com/heroku/heroku-buildpack-php/blob/master/bin/util/platform.php#L158) as `$require["heroku-sys-apache-module/modsecurity"] = "~2.9.1";`.

What do you think of it?

**Comment by dzuelke** [comment]
You could, but what would that gain you? Then it's statically coded into the buildpack, which you need to run a fork of, so you could just as well compile it into Apache itself, because then at least you don't have to run a forked buildpack that you need to keep up to date...

I've been thinking previously that an `extra` section in `composer.json` could be done, where one can specify Apache or Nginx versions, and then maybe modules like this... but not sure if that's really worth the effort. Most people are running just fine with the stock set of modules, or build their own package of Apache with the modules they need.

**Comment by luka-zitnik** [comment]
Got it. It would compile faster, but there's a new buildpack and it would have to be maintained. Didn't think of that. You've just stopped me from doing a stupid thing. Thank you for that.

I like the idea of using the `extra` section of composer. That satisfies my interest in widening my view of the project. So I'm good if you want to close this thread now. Or leave it if you'd expect feedback from people wanting the feature.

I also think people are fine with building their own packages, judging solely by the large number of forks this project has and it surely is amusing building one on my own.

**Comment by dzuelke** [comment]
To maintain your own packages, instead of forking the whole buildpack, you can also just maintain the package formulae, like @stof does here: https://github.com/Incenteev/heroku-php-exts

I'll rework the formulae a little in the future and add some more tooling to make this approach a bit more convenient out of the box.

**Comment by luka-zitnik** [comment]
Great link David! Thanks!
