### ISSUE TITLE
php.ini for command line php scripts (symfony cli)

### ISSUE THREAD

**Issue by ProGM** [heroku/heroku-buildpack-php#224]
I'm using a symfony2 app using this buildpack.
Here's my `Procfile`:
```
web: vendor/bin/heroku-php-apache2 web/
```

In my `web` folder I created a `.user.ini` file, following the heroku docs:

```ini
upload_max_filesize = 20M
post_max_size = 28M
date.timezone = Europe/Rome
session.save_handler=memcached
session.save_path="${MEMCACHEDCLOUD_SERVERS}"
memcached.sess_binary_protocol=1 # for ext-memcached 3 / PHP 7
memcached.sess_sasl_username="${MEMCACHEDCLOUD_USERNAME}"
memcached.sess_sasl_password="${MEMCACHEDCLOUD_PASSWORD}"
memcached.sess_persistent=On
```

This is running fine when loading web pages.
However, all symfony cli scripts are ignoring this php.ini file changes.

My major problem is the `date.timezone`.

Temporary, I monkey patched the `bin/console` script, adding:

```php
date_default_timezone_set("Europe/Rome");
```

Is there a way to define a custom php.ini file for shell-based php scripts using this buildpack?

**Comment by dzuelke** [comment]
Yeah `.user.ini` is only picked up by PHP-FPM.

Generally, if your code relies on that timezone, then in the interest of portability, you should have that timezone setting in your code; otherwise, it will behave differently in different environments.

Another alternative of course is to invoke the worker/script with `php -ddate.timezone=Europe/Rome bin/console …`.
