### ISSUE TITLE
About Zend Guard Loader Server Extension

### ISSUE THREAD

**Issue by mozgbrasil** [heroku/heroku-buildpack-php#228]
# en_US

Hello

good evening

I have the following application available in

https://github.com/mozgbrasil/heroku-magento#implantando-na-heroku

When I run to deploy

You receive the following error message "Your requirements could not be resolved to an installable set of packages."

This error started to occur after I added in the composer.json file the following item as required

    "require": {
    	...
        "ext-zend-guard-loader": "*"

See for this application I have the Zend Guard Loader

https://magento-heroku.herokuapp.com/?phpinfo=true

On other servers when Zend Guard Loader is informed, it works normally when reporting this request on composer.json

Does anyone have any tips to help me?

--

![captura de tela de 2017-05-10 20-20-05](https://cloud.githubusercontent.com/assets/17202780/25925478/3a932304-35bf-11e7-8eb1-33e75938d964.png)
![captura de tela de 2017-05-15 15-11-22](https://cloud.githubusercontent.com/assets/17202780/26072108/d0a7bec6-3980-11e7-8edf-84c83507a5ad.png)
![captura de tela de 2017-05-10 20-55-55](https://cloud.githubusercontent.com/assets/17202780/25926073/16e1abe8-35c3-11e7-9e74-35e5a9312a5e.png)
![captura de tela de 2017-05-15 15-25-30](https://cloud.githubusercontent.com/assets/17202780/26072799/48c3b9c6-3983-11e7-8498-6773c5739bd8.png)
![captura de tela de 2017-05-15 15-25-48](https://cloud.githubusercontent.com/assets/17202780/26072797/48c1c6f2-3983-11e7-8145-36146d342c5b.png)
![captura de tela de 2017-05-15 15-27-05](https://cloud.githubusercontent.com/assets/17202780/26072798/48c238bc-3983-11e7-9b5d-ccf01d18ece5.png)
![captura de tela de 2017-05-15 15-28-02](https://cloud.githubusercontent.com/assets/17202780/26072800/48c56f64-3983-11e7-9ce5-cb3458287954.png)

**Comment by dzuelke** [comment]
Unfortunately, Zend Guard Loader is not supported on Heroku, and as Zend have stopped development of that product and will not port it to PHP 7, we have no plans to add support for it.

It is possible to host your own extensions in e.g. an S3 bucket. For instructions, please see https://github.com/heroku/heroku-buildpack-php/blob/master/support/build/README.md and use the `newrelic` formulae as a template, as they also only download an existing built `.so` extension binary instead of building an extension from source.

Please understand that Heroku cannot provide support for issues you encounter when using this method.
