### ISSUE TITLE
Failed to download minimal PHP for bootstrapping. (7.0.26)

### ISSUE THREAD

**Issue by HillLiu** [heroku/heroku-buildpack-php#249]
```
-----> Cleaning up...
-----> Building force from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> PHP app detected
-----> Bootstrapping...
       
       !     ERROR: Failed to download minimal PHP for bootstrapping.
       Please try again, or contact support if this problem persists.
```

https://github.com/heroku/heroku-buildpack-php/commit/4428a20862137d682c9c15434c82a65c20541f97

**Comment by behzadsh** [comment]
I have the same issue!

**Comment by dzuelke** [comment]
You're running forked versions of the buildpack, or old revisions. Please update your forks, stop using forks (you usually don't need them), or set your app to use the latest release.

**Comment by codestation** [comment]
Hi, so the bug was caused because the php binaries where removed from S3? For how long are these stored? (translated to "how much time are old buildpacks supported"?). Right now dokku uses herokuish 0.3.32 who ships with the revision v122 of this buildpack (3 months old). If the time is fixed then is good idea to alert the dokku folks so they updated herokuish within a certain timeframe.

**Comment by HillLiu** [comment]
BTW, for now it could be resolved by upgrade herokuish from source

http://dokku.viewdocs.io/dokku/getting-started/upgrading/#upgrade-from-source

**Comment by dzuelke** [comment]
We periodically clean up stale packages from S3, as their continued presence leads to ever longer synchronization times between repositories upon release of new versions. Generally, also because of the mechanics of how a buildpack gets rolled out, the previous minimal PHP for bootstrapping, as well as the previous Composer release, will usually be available until the release of the next respective versions, but older versions may be cleaned up. That translates to roughly monthly rollovers.
