### ISSUE TITLE
Newrelic extension is missing since PHP 7.3

### ISSUE THREAD

**Issue by fedeisas** [heroku/heroku-buildpack-php#312]
Just deployed my app and it picked on the new php7.3 version without changing my code. But New Relic stopped working.

Should I fix my PHP version somehow with composer?

**Comment by johnutzm** [comment]
Hello,
yes, you can select the PHP version in composer.json
https://devcenter.heroku.com/articles/php-support#selecting-a-runtime

**Comment by ajoy39** [comment]
We are having the same issue. since php 7.3 starting deploying this morning no data has been passed to newrelic. We lost an entire working days worth of logs before someone caught this. 

@fedeisas for now you can define a php version in your composer.json file so long as you can roll back to php 7.2.*

**Comment by dzuelke** [comment]
New Relic simply haven't released an update with PHP 7.3 support yet. This is also documented at https://devcenter.heroku.com/changelog-items/1536.

For production apps, I recommend locking down your PHP version requirement more tightly (e.g. with `~7.2.0`), and/or explicitly depending on `ext-newrelic` in `require` (you can use `config.platform` to pretend `ext-newrelic` is there for local dev envs) to prevent these situations.

**Comment by dzuelke** [comment]
(FYI, the current behavior where `ext-newrelic` is auto-installed at the end of the build when detected comes from a time before Composer had the `config.platform` feature, and we wanted a way for users to use the extension without having to `--ignore-platform-reqs` all the time locally because of `ext-newrelic` in `require`)

**Comment by dzuelke** [comment]
`ext-newrelic` is now available for PHP 7.3: https://devcenter.heroku.com/changelog-items/1541
