### ISSUE TITLE
Update default concurrency for PX dynos

### ISSUE THREAD

**Issue by mksm** [heroku/heroku-buildpack-php#325]
Hi!

I believe available memory for PX dynos be updated to 14G:

https://github.com/heroku/heroku-buildpack-php/blob/e19cd3062208c1be2ad90130744a048abadc434b/bin/heroku-php-nginx#L301-L306

Reference: https://devcenter.heroku.com/articles/dyno-types

**Comment by dzuelke** [comment]
Yes. This is currently still the old default because simply changing it would break existing working applications: a higher number of FPM processes would be spawned, and then applications would run into e.g. database connection limits.

This will be fixed soon, it just needs a bit of a complicated migration process and some time for customer outreach.

**Comment by stof** [comment]
Fixed by #329

**Comment by jyhuang-japan** [comment]
Is there any update ?
