### ISSUE TITLE
Is WEB_CONCURRENCY set being set correctly

### ISSUE THREAD

**Issue by dwightwatson** [heroku/heroku-buildpack-php#369]
This looks semi-related to #325 - but it revolves around the optimisation of the `WEB_CONCURRENCY` setting which [appears to come from this section of code](https://github.com/heroku/heroku-buildpack-php/blob/168f61a2f8b8eeb1ff8394227fba170e35851f07/bin/heroku-php-apache2#L326-L352).

I'm running Performance M instances - which have 2.5GB of RAM. According to [this Heroku documentation](https://devcenter.heroku.com/articles/php-concurrency#web_concurrency-defaults) default `WEB_CONCURRENCY` for this instance type is 20.

However, upon looking at the logs it appears to be set to 5.

```
app web.1 - - Using WEB_CONCURRENCY=5 processes.
```

I've not set this anywhere as far as I'm aware - it's not an environment variable, and doesn't appear to be set in config either (`heroku config:get WEB_CONCURRENCY` returns nothing).

Is this an issue with the buildpack incorrectly inferring or setting `WEB_CONCURRENCY`?

**Comment by dwightwatson** [comment]
It may not be PX specific - my staging environment using Standard 1x dynos. This has 512MB RAM and according to the same documentation above it should have a default `WEB_CONCURRENCY` of 4. 

The launch logs show that it instead only has 1.

```
app[web.1]: Using WEB_CONCURRENCY=1 processes.
```

**Comment by dzuelke** [comment]
It's because you're using `heroku/nodejs` together with `heroku/php`, but you have the order set incorrectly. If Node.js buildpack runs after the PHP buildpack, its defaults for `$WEB_CONCURRENCY` will win. The last buildpack in the list determines the app type.

Swap the order using `heroku buildpacks`, and if needed, use the `composer compile` script to invoke `node` or whatever you want from inside the PHP buildpack.

**Comment by CaitlinWeb** [comment]
The order of the nodejs and php buildpacks is still important but I think it should now be reversed, with php first. [Since last month](https://github.com/heroku/heroku-buildpack-nodejs/blame/1195e9b2949d852f400702fd863650cc44603167/profile/WEB_CONCURRENCY.sh) the nodejs buildpack checks if `WEB_CONCURRENCY` is set before setting it. The PHP buildpack [does the same](https://github.com/heroku/heroku-buildpack-php/blame/6c579f59f0d1b3e47d8bd90e8784c4c5a3851625/bin/heroku-php-nginx#L404).

I found this issue when looking into why my app's `WEB_CONCURRENCY` is wrong. My app has it currently set to `28` but according to [the documentation](https://devcenter.heroku.com/articles/php-concurrency#web_concurrency-defaults) it should be `112`!

**Comment by edmorley** [comment]
@CaitlinWeb The recommended order of buildpacks has not changed - the primary language buildpack should still go last. I believe the issue you are encountering must be something else (for which filing a new issue is best).

The way most of the language buildpacks set `WEB_CONCURRENCY` dynamically, is by adding a `.profile.d/WEB_CONCURRENCY.sh` script into the slug. Later buildpacks will overwrite the `WEB_CONCURRENCY.sh` of earlier buildpacks, so the last buildpack wins (even though inside the scripts there are checks for whether the env var is already set, as you noted).

For PHP, things are a bit different in that the dynamic calculation of concurrency occurs via the `heroku-php-nginx` or `heroku-php-apache2` startup scripts that Heroku PHP apps will have listed in their Procfile. However, during the build the PHP buildpack still overwrites the `WEB_CONCURRENCY.sh` script of any earlier buildpack with a blank file to make sure those earlier buildpacks don't interfere with the value calculated in `heroku-php-nginx` / `heroku-php-apache2`. 

See:
https://github.com/heroku/heroku-buildpack-php/blob/6c579f59f0d1b3e47d8bd90e8784c4c5a3851625/bin/compile#L778-L779
