### ISSUE TITLE
Composer "test" not running

### ISSUE THREAD

**Issue by 090809** [heroku/heroku-buildpack-php#388]
Composer run-script test not running, but "test" is present in composer.json.
Previously (yesterday) it work's fine.

SMTH goes wrong?

**Comment by dzuelke** [comment]
Sorry but this is info is a bit meager... please provide more info, otherwise this is a useless bug report that we can't do anything about.

- are you using Heroku CI?
- what does "not running" mean? 
- is Heroku CI erroring, or failing?
- what's the error message?
- what stack are you on?
- what version of PHP are you on?
- what version of PHP were you on previously?
- is this failure on the same app that worked before, or a new app?
- etc etc etc

**Comment by 090809** [comment]
Using Gitlab Ci
Not running - fails in "phpunit", cause composer run-script test doen't start
Using - php (7.4.2)
No any updates was done. It's start crash at test in 2 different projects at same time.
And it crash in any new project

Thanks for reply

**Comment by dzuelke** [comment]
So it's using Herokuish or something, on Gitlab CI?

Sorry, can't provide support for that. You need to figure it out yourself. Might be PHP 7.4 related.

**Comment by mkopinsky** [comment]
I'm getting the same problem on heroku, with PHP 7.4.

```
-----> Running PHP buildpack tests...
Trying to auto-detect test framework; first match will be found. You may use composer script 'test', or app.json, to specify what to run.
No tests found. Please use composer script 'test', or app.json, to specify what to run.
-----> PHP buildpack tests failed with exit status 1
```

My composer does have a test script in composer.json and this used to work. Forcing PHP <7.4.0 (i.e. using 7.3.14) it does work.

If you have heroku sudo power and want to look at logs, feel free: https://dashboard.heroku.com/pipelines/d8323639-09f9-4e7e-b697-212bc21c3418/tests/335

Otherwise I'm happy to share whatever else would help debug.

**Comment by dzuelke** [comment]
Is this still an issue for people? I can't reproduce it; it works fine in our CI tests too (there's a bunch of test cases just for this stuff).

**Comment by 090809** [comment]
After v174 this error didn't appear

**Comment by dzuelke** [comment]
Bizarre. Nothing changed other than the usual PHP version bumps. But who knows, might have been a runtime bug. Glad to hear it's sorted!

**Comment by dzuelke** [comment]
Found out the reason.

In PHP 7.4, `fwrite()` now returns a `false`y status more often. This can sometimes happen when e.g. running `program | grep -q thismatches`, then `grep` closes `stdin` upon a match and `program` will not be able to write output, causing an error.

This is worked around in Symfony: https://github.com/symfony/symfony/pull/36222, but internally, Composer uses really old versions of course for BC with older PHP releases.
