### ISSUE TITLE
Nginx rights problems

### ISSUE THREAD

**Issue by limbah** [heroku/heroku-buildpack-php#426]
Hello I have a problem with the deployment of my application. 
When I push my app everything is fine, but when I connect this last crash. 
Looking at the logs it seems to me that it is an nginx problem that cannot write to the logs. 

Thank you
[logs.txt](https://github.com/heroku/heroku-buildpack-php/files/5083003/logs.txt)

**Comment by dzuelke** [comment]
That error most likely means `/app/.heroku/php/var/log/nginx/` doesn't exist.

That directory, however, is part of the Nginx tarball:

```
$ curl -s https://lang-php.s3.amazonaws.com/dist-heroku-18-stable/nginx-1.18.0.tar.gz | tar tz | grep log
var/log/
var/log/nginx/
```

So it looks like it's getting deleted somewhere when you build your app. Are you doing anything special during your deploy? Are you on the latest version of everything (buildpack not pinned to an old release etc)?

Since this appears to be a Heroku app, can you please file a support ticket at https://help.heroku.com, point to this GitHub issue, and ask for escalation?

**Comment by dzuelke** [comment]
Solved via support ticket: the pushed app source for some reason contained all files from a runtime dyno instance, including `.heroku/` with the entire runtime PHP installation Heroku installs at build time, and `.profile.d/`, which messed up the build and caused this. Closing here.

**Comment by limbah** [comment]
I just read the ticket, and thanks to your solution I was able to solve my problem.
Thank you very much for your involvement!
