### ISSUE TITLE
Making repositories

### ISSUE THREAD

**Issue by tillkruss** [heroku/heroku-buildpack-php#468]
I'm a little confused about the [extension build instructions](https://github.com/heroku/heroku-buildpack-php/tree/main/support/build#building-a-new-extension-using-heroku-tooling-and-composer).

It's showing a `bob build` for each stack (`heroku-18, heroku-20, ...`), but then just a single `heroku-20 mkrepo.sh --upload` call on the `heroku-20` stack.

Am I suppose to call `mkrepo.sh` for each stack individually, or is the `mkrepo.sh` broken since it's only generating the `packages.json` for the `heroku-20` stack for me?

I addition to that, is it advised to have a dedicated repository for each stack?

```
https://foobar-ext.s3.amazonaws.com/dist-heroku-18-develop/
https://foobar-ext.s3.amazonaws.com/dist-heroku-18-stable/
https://foobar-ext.s3.amazonaws.com/dist-heroku-20-develop/
https://foobar-ext.s3.amazonaws.com/dist-heroku-20-stable/
```

**Comment by dzuelke** [comment]
Yeah the repository operations are all exclusive to that repository. `mkrepo.sh` doesn't even know about your other prefixes if it's currently operating on the one for heroku-20. Later example commands are just not repeated in the docs for all permutations since the assumption was it's obvious at some point ;)

You can also lump all the builds together in one repo, but you then have to ensure that your package and manifest filenames are different per stack, which gets nasty quickly, so internally, we have one repo per stack (it also reduces repository size significantly, which starts to matter for syncing etc, since these are all slow S3 operations).

Of course, if your extension is portable enough and doesn't even link against libraries that differ between the stacks (i.e. if their ABI version number is the same), you can just build on the oldest (!) stack (the deprecated heroku-16 if you still want to support it, or heroku-18 if not), and it should (tm) just (R) work fine for all stacks in most cases.

In that case you can also forego the `heroku-sys/heroku` requirement described in https://github.com/heroku/heroku-buildpack-php/tree/3e49045a63ed480378c9d3d3e364acbfcc06eb3f/support/build#minimum-information

**Comment by tillkruss** [comment]
Thanks so much, I'll stick with the standard approach 👍

**Comment by dzuelke** [comment]
Well, what are you building? You can, after `bob build`, `ldd /app/.heroku/php/lib/php/extensions/no-debug-non-zts-*/yourext.so` and see what it links against... if the output is the same for all your stacks (or you can tell from the list and x-refing https://devcenter.heroku.com/articles/stack-packages that the ABI versions are the same for all linked libs), then you don't need a repo per stack.

But even if not, then the day will likely come where you do, because another ext you build links against OpenSSL or whatever where the ABI versions differ between the OSes, so maybe have separate repos from the start to not have to migrate later.

**Comment by tillkruss** [comment]
@dzuelke I'm building a repository for PhpRedis, but with igbinary support, as well as the igbinary extension. 

PhpRedis also has compressions enabled that use `liblzf-dev`, `libzstd-dev` and `liblz4-dev`, so plenty of dependencies. 

It's all groundwork for distributing [Relay](https://relaycache.com), which we aim to be launch by the end of the month. 

Using separate repos for each stack seems to be the safest approach, thanks for all the details! 🙏🏻

**Comment by tillkruss** [comment]
@dzuelke If you're curios, I just pushed the repo live: https://github.com/cachewerk/heroku-php-extensions

PhpRedis on Heroku with support for igbinary, LZF, LZ4 and zstd compression.
